
import React from 'react';
import { EACCountry } from './types';

export const EAC_METADATA: Record<EACCountry, { currency: string, vat: number, authority: string, bodies: string }> = {
  Uganda: { currency: 'UGX', vat: 0.18, authority: 'URA (Uganda Revenue Authority)', bodies: 'ICPAU' },
  Kenya: { currency: 'KES', vat: 0.16, authority: 'KRA (Kenya Revenue Authority)', bodies: 'ICPAK' },
  Tanzania: { currency: 'TZS', vat: 0.18, authority: 'TRA (Tanzania Revenue Authority)', bodies: 'NBAA' },
  Rwanda: { currency: 'RWF', vat: 0.18, authority: 'RRA (Rwanda Revenue Authority)', bodies: 'ICPAR' },
  Burundi: { currency: 'BIF', vat: 0.18, authority: 'OBR (Office Burundais des Recettes)', bodies: 'OPC' },
  SouthSudan: { currency: 'SSP', vat: 0.15, authority: 'NRA (National Revenue Authority)', bodies: 'SSAA' },
  DRC: { currency: 'CDF', vat: 0.16, authority: 'DGI (Direction Générale des Impôts)', bodies: 'ONEC' },
  Somalia: { currency: 'USD', vat: 0.05, authority: 'Ministry of Finance', bodies: 'SIMA' }
};

export const TRANSLATIONS = {
  en: {
    auditorPortal: 'EAC Auditor Portal',
    clientPortal: 'Client Portal',
    manageClients: 'Manage Clients',
    clientPortfolio: 'EAC Client Portfolio',
    complianceSummary: 'Regional Compliance',
    anomaliesFound: 'Anomalies Detected',
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    taxCompliance: 'Tax Compliance',
    auditAssistant: 'Audit Assistant',
    settings: 'Settings',
    totalIncome: 'Total Income',
    totalExpense: 'Total Expenses',
    taxLiabilities: 'Tax Liabilities',
    scanReceipt: 'Scan Receipt',
    addTransaction: 'Add Transaction',
    cashflowOverview: 'Cashflow Overview',
    recentAnomalies: 'Recent Anomalies',
    vatRate: 'VAT',
    whtRate: 'WHT',
    lstRate: 'LST',
    uraReturns: 'Authority Filing (XML)',
    generateReport: 'Generate Report',
    welcome: 'Welcome to EAC-Auditor',
    tagline: 'Empowering EAC Businesses with AI-driven compliance',
    aiChat: 'mugisolo AI Advisory',
    askAnything: 'Ask mugisolo about EAC tax, audit, or regional standards...',
    imageAnalysis: 'Analyze Document',
    dropImage: 'Upload document for AI analysis',
    nearbyServices: 'Nearby Accounting Services',
    thinkingMode: 'Deep Reasoning Mode',
    deepThinkDesc: 'Uses advanced thinking for complex EAC regulations',
    invoiceNumber: 'Invoice #',
    dueDate: 'Due Date',
    all: 'All',
    income: 'Income',
    expense: 'Expense',
    customCategories: 'Custom Categories',
    addCategory: 'Add Category',
    taxBreakdown: 'Regional Tax Breakdown',
    reviewTransaction: 'Review Extracted Details',
    switchToAuditor: 'Switch to Auditor View',
    switchToClient: 'Switch to Client View',
    evidenceCollection: 'Evidence Collection',
    continuousMonitoring: 'Continuous Monitoring',
    trustScore: 'Trust Score',
    automatedTests: 'Compliance Tests',
    hqLocation: 'Business Headquarters',
    workflow: 'Audit Workflow',
    dueDiligence: 'Due Diligence',
    searchClients: 'Search clients by name or TIN...',
    sortBy: 'Sort By',
    complianceAlerts: 'Compliance Alerts',
    thresholds: 'Alert Thresholds',
    lowScoreAlert: 'Low Compliance Score Alert (%)',
    highIssuesAlert: 'High Issues Count Alert',
    deadlineAlert: 'Deadline Notification Days',
    auditHub: 'Audit Hub'
  },
  lg: {
    auditorPortal: 'Embuga ya Auditor (EAC)',
    clientPortal: 'Embuga ya Kiliyanti',
    manageClients: 'Ddukanya Bakiliyanti',
    clientPortfolio: 'Bakiliyanti ba EAC',
    complianceSummary: 'Obusulu bw’ekitundu',
    anomaliesFound: 'Ebireetedwa AI',
    dashboard: 'Ekituufu',
    transactions: 'Ebisasulwa',
    taxCompliance: 'Eby’omusolo',
    auditAssistant: 'Omuyambi w’okukebera',
    settings: 'Enteekateeka',
    totalIncome: 'Sente eziyingidde',
    totalExpense: 'Sente ezafulumye',
    taxLiabilities: 'Ebibanja by’omusolo',
    scanReceipt: 'Kuba risiti ekipica',
    addTransaction: 'Yongerako ebisasulwa',
    cashflowOverview: 'Okutambula kwa sente',
    recentAnomalies: 'Ebitagenda bulungi',
    vatRate: 'VAT',
    whtRate: 'WHT',
    lstRate: 'LST',
    uraReturns: 'Ebiwandiiko bya URA',
    generateReport: 'Funa alipoota',
    welcome: 'Tukusanyukidde mu EAC-Auditor',
    tagline: 'Okunyweza amakampuni ga EAC n’amagezi ga AI',
    aiChat: 'Emboozi ya mugisolo AI',
    askAnything: 'Buuza mugisolo ku musolo gwa EAC...',
    imageAnalysis: 'Kebera ekiwandiiko',
    dropImage: 'Teekayo ekiwandiiko AI akikebere',
    nearbyServices: 'Aba accountant abali okumpi',
    thinkingMode: 'Okulowooza okukule',
    deepThinkDesc: 'AI akozesa obuyiiya obunene ku bibuuzo ebizibu',
    invoiceNumber: 'Invoisi #',
    dueDate: 'Olunaku lw’okusasula',
    all: 'Byonna',
    income: 'Eziyingidde',
    expense: 'Ezafulumye',
    customCategories: 'Ebika ebipya',
    addCategory: 'Yongerako ekika',
    taxBreakdown: 'Omuwendo gw’omusolo',
    reviewTransaction: 'Kebera ebisangiddwa',
    switchToAuditor: 'Kyusa ogende mu Auditor',
    switchToClient: 'Kyusa ogende mu Kiliyanti',
    evidenceCollection: 'Okukuŋŋaanya Obujulizi',
    continuousMonitoring: 'Okukebera Okunene',
    trustScore: 'Obuyigirize bwa Trust',
    automatedTests: 'Ebigezo by’obusulu',
    hqLocation: 'Office Enkulu',
    workflow: 'Audit Workflow',
    dueDiligence: 'Due Diligence',
    searchClients: 'Search clients by name or TIN...',
    sortBy: 'Sort By',
    complianceAlerts: 'Compliance Alerts',
    thresholds: 'Alert Thresholds',
    lowScoreAlert: 'Low Compliance Score Alert (%)',
    highIssuesAlert: 'High Issues Count Alert',
    deadlineAlert: 'Deadline Notification Days',
    auditHub: 'Audit Hub'
  },
  sw: {
    auditorPortal: 'Portal ya Mkaguzi wa EAC',
    clientPortal: 'Portal ya Mteja',
    manageClients: 'Dhibiti Wateja',
    clientPortfolio: 'Portfolio ya Wateja wa EAC',
    complianceSummary: 'Uzingatiaji wa Kikanda',
    anomaliesFound: 'Hitilafu Zilizogunduliwa',
    dashboard: 'Dashibodi',
    transactions: 'Miamala',
    taxCompliance: 'Uzingatiaji wa Kodi',
    auditAssistant: 'Msaidizi wa Ukaguzi',
    settings: 'Mipangilio',
    totalIncome: 'Mapato Jumla',
    totalExpense: 'Gharama Jumla',
    taxLiabilities: 'Deni la Kodi',
    scanReceipt: 'Changanua Risiti',
    addTransaction: 'Ongeza Muamala',
    cashflowOverview: 'Muhtasari wa Mtiririko wa Fedha',
    recentAnomalies: 'Hitilafu za Hivi Karibuni',
    vatRate: 'VAT',
    whtRate: 'WHT',
    lstRate: 'LST',
    uraReturns: 'Ripoti za Mamlaka',
    generateReport: 'Tengeneza Ripoti',
    welcome: 'Karibu EAC-Auditor',
    tagline: 'Kuwezesha Biashara za EAC kwa utiifu wa AI',
    aiChat: 'Mazungumzo ya mugisolo AI',
    askAnything: 'Uliza mugisolo kuhusu kodi ya EAC...',
    imageAnalysis: 'Changanua Hati',
    dropImage: 'Pakia hati kwa uchambuzi wa AI',
    nearbyServices: 'Huduma za Uhasibu Karibu',
    thinkingMode: 'Hali ya Kufikiri Sana',
    deepThinkDesc: 'AI hutumia mawazo ya juu kwa maswali magumu ya EAC',
    invoiceNumber: 'Nambari ya Ankara',
    dueDate: 'Tarehe ya Malipo',
    all: 'Zote',
    income: 'Mapato',
    expense: 'Gharama',
    customCategories: 'Aina Maalum',
    addCategory: 'Ongeza Aina',
    taxBreakdown: 'Mchanganuo wa Kodi',
    reviewTransaction: 'Hakiki Maelezo',
    switchToAuditor: 'Badili kwenda Mkaguzi',
    switchToClient: 'Badili kwenda Mteja',
    evidenceCollection: 'Ukusanyaji wa Ushahidi',
    continuousMonitoring: 'Ufuatiliaji Unaoendelea',
    trustScore: 'Alama ya Imani',
    automatedTests: 'Vipimo vya Uzingatiaji',
    hqLocation: 'Makao Makuu',
    workflow: 'Audit Workflow',
    dueDiligence: 'Due Diligence',
    searchClients: 'Search clients by name or TIN...',
    sortBy: 'Sort By',
    complianceAlerts: 'Compliance Alerts',
    thresholds: 'Alert Thresholds',
    lowScoreAlert: 'Low Compliance Score Alert (%)',
    highIssuesAlert: 'High Issues Count Alert',
    deadlineAlert: 'Deadline Notification Days',
    auditHub: 'Audit Hub'
  }
};

export const ICONS = {
  Dashboard: () => <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="7" height="7"></rect><rect x="14" y="3" width="7" height="7"></rect><rect x="14" y="14" width="7" height="7"></rect><rect x="3" y="14" width="7" height="7"></rect></svg>,
  Transactions: () => <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path></svg>,
  Tax: () => <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>,
  Audit: () => <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>,
  Settings: () => <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1-2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path></svg>,
  Camera: () => <svg xmlns="http://www.w3.org/2000/svg" className="w-6 h-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>,
  Chat: () => <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path></svg>,
  Send: () => <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="22" y1="2" x2="11" y2="13"></line><polygon points="22 2 15 22 11 13 2 9 22 2"></polygon></svg>,
  MapPin: () => <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>,
  ChevronDown: () => <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="6 9 12 15 18 9"></polyline></svg>,
  ChevronUp: () => <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="18 15 12 9 6 15"></polyline></svg>,
  Users: () => <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>,
  Shield: () => <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>,
  Verified: () => <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline></svg>,
  Filter: () => <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"></polygon></svg>,
  Clock: () => <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>,
};
